user.service.base-url=http://user-service:8081
device.service.base-url=http://device-service:8082
ingestion.service.base-url=http://ingestion-service:8083
usage.service.base-url=http://usage-service:8084
alert.service.base-url=http://alert-service:8085

