server.port=8000

user.service.fallback-url=forward:/fallback/users
device.service.fallback-url=forward:/fallback/devices
ingestion.service.fallback-url=forward:/fallback/ingestion
usage.service.fallback-url=forward:/fallback/usage
alert.service.fallback-url=forward:/fallback/alert

spring.security.oauth2.resourceserver.jwt.issuer-uri=${TOKEN_ISSUER_URI}

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true