user.service.base-url=http://user-service:8081
device.service.base-url=http://device-service:8082

spring.datasource.url=jdbc:postgresql://timescaledb:5432/${TIMESCALEDB_NAME}
spring.datasource.username=${TIMESCALEDB_USERNAME}
spring.datasource.password=${TIMESCALEDB_PASSWORD}