user.service.base-url=http://localhost:8081
device.service.base-url=http://localhost:8082

spring.datasource.url=jdbc:postgresql://localhost:5432/${TIMESCALEDB_NAME}
spring.datasource.username=${TIMESCALEDB_USERNAME}
spring.datasource.password=${TIMESCALEDB_PASSWORD}