spring.application.name=ingestion-service

#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:https://config-server-latest-u7f5.onrender.com
spring.profiles.active=docker
