spring.application.name=config-server
server.port=8888

# Spring Cloud Config Server configuration
spring.cloud.config.server.native.search-locations=\
  classpath:/config/global,\
  classpath:/config/user-service,\
  classpath:/config/device-service,\
  classpath:/config/ingestion-service, \
  classpath:/config/usage-service,\
  classpath:/config/alert-service, \
  classpath:/config/api-gateway

spring.profiles.active=native

