name: Build and Push Module

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Select module to build"
        required: true
        type: choice
        options:
          - config-server
          - api-gateway
          - user-service
          - device-service
          - ingestion-service
          - alert-service
          - insight-service

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: voltly

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven


      - name: Generate image tag
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short=7 HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV


      - name: Build selected module
        run: |
          mvn clean package \
            -pl ${{ github.event.inputs.module }} \
            -am \
            -DskipTests


      - name: Find generated JAR
        id: jar
        run: |
          MODULE=${{ github.event.inputs.module }}
          JAR_FILE=$(find ./${MODULE}/target \
            -name "*.jar" \
            ! -name "*sources.jar" \
            ! -name "*javadoc.jar" \
            ! -name "original-*.jar" | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "Found jar: $JAR_FILE"


      - name: Create Dockerfile dynamically
        run: |
          run: |
            MODULE=config-server
            DOCKERFILE_PATH=./${MODULE}/Dockerfile
          
            if [ ! -f "$DOCKERFILE_PATH" ]; then
              echo 'FROM eclipse-temurin:21-jre' > "$DOCKERFILE_PATH"
              echo 'COPY target/*.jar app.jar' >> "$DOCKERFILE_PATH"
              echo 'ENTRYPOINT ["java", "-jar", "/app.jar"]' >> "$DOCKERFILE_PATH"
            fi


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker image
        run: |
          MODULE=${{ github.event.inputs.module }}
          IMAGE=ghcr.io/${{ github.repository_owner }}/${MODULE}
          docker build \
            -t $IMAGE:${SHORT_SHA} \
            -t $IMAGE:latest \
            ./${MODULE}


      - name: Push Docker image
        run: |
          MODULE=${{ github.event.inputs.module }}
          IMAGE=ghcr.io/${{ github.repository_owner }}/${MODULE}
          docker push $IMAGE:${SHORT_SHA}
          docker push $IMAGE:latest